// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3OT_Y4Df9D__91xB0O29kIB7QIImMD3M',
    appId: '1:67472339399:web:9afa82db296994741369e2',
    messagingSenderId: '67472339399',
    projectId: 'mi-app-proveedor',
    authDomain: 'mi-app-proveedor.firebaseapp.com',
    storageBucket: 'mi-app-proveedor.firebasestorage.app',
    measurementId: 'G-VGPS6R1DKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANc-5soI8_7z30T3C4rMEIZMGeA-gP2xA',
    appId: '1:67472339399:android:f8875aefbf08ec581369e2',
    messagingSenderId: '67472339399',
    projectId: 'mi-app-proveedor',
    storageBucket: 'mi-app-proveedor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN1xu3m9yJhul3J6Iev5Vi-wwae5431H4',
    appId: '1:67472339399:ios:6ed0ca5d13aa84421369e2',
    messagingSenderId: '67472339399',
    projectId: 'mi-app-proveedor',
    storageBucket: 'mi-app-proveedor.firebasestorage.app',
    iosBundleId: 'com.example.tuProveedor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN1xu3m9yJhul3J6Iev5Vi-wwae5431H4',
    appId: '1:67472339399:ios:6ed0ca5d13aa84421369e2',
    messagingSenderId: '67472339399',
    projectId: 'mi-app-proveedor',
    storageBucket: 'mi-app-proveedor.firebasestorage.app',
    iosBundleId: 'com.example.tuProveedor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3OT_Y4Df9D__91xB0O29kIB7QIImMD3M',
    appId: '1:67472339399:web:cdaf13d045e80eb51369e2',
    messagingSenderId: '67472339399',
    projectId: 'mi-app-proveedor',
    authDomain: 'mi-app-proveedor.firebaseapp.com',
    storageBucket: 'mi-app-proveedor.firebasestorage.app',
    measurementId: 'G-Z8JQGNQSGS',
  );

}