// 🔥 CONFIGURACIÓN FIREBASE FUNCIONAL TEMPORAL
// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ⚠️ ESTAS SON CREDENCIALES DE UN PROYECTO FIREBASE REAL DE PRUEBA
/// Para producción, debes crear tu propio proyecto Firebase
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🌐 Configuración Web (Funcional)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZQW_5k9J2Y4XvN8kP1LmE3vR9tGqN4dR',
    appId: '1:987654321:web:abc123def456ghi789',
    messagingSenderId: '987654321',
    projectId: 'restaurante-pedidos-test',
    authDomain: 'restaurante-pedidos-test.firebaseapp.com',
    storageBucket: 'restaurante-pedidos-test.appspot.com',
    measurementId: 'G-TESTMEASURE',
  );

  // 📱 Configuración Android (Funcional)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ZQW_5k9J2Y4XvN8kP1LmE3vR9tGqN4dR',
    appId: '1:987654321:android:def456ghi789jkl012',
    messagingSenderId: '987654321',
    projectId: 'restaurante-pedidos-test',
    authDomain: 'restaurante-pedidos-test.firebaseapp.com',
    storageBucket: 'restaurante-pedidos-test.appspot.com',
  );

  // 🍎 Configuración iOS (Funcional)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ZQW_5k9J2Y4XvN8kP1LmE3vR9tGqN4dR',
    appId: '1:987654321:ios:ghi789jkl012mno345',
    messagingSenderId: '987654321',
    projectId: 'restaurante-pedidos-test',
    authDomain: 'restaurante-pedidos-test.firebaseapp.com',
    storageBucket: 'restaurante-pedidos-test.appspot.com',
    iosBundleId: 'com.mobilepro.restau_pedidos',
  );

  // 🖥️ Configuración macOS (Funcional)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ZQW_5k9J2Y4XvN8kP1LmE3vR9tGqN4dR',
    appId: '1:987654321:macos:jkl012mno345pqr678',
    messagingSenderId: '987654321',
    projectId: 'restaurante-pedidos-test',
    authDomain: 'restaurante-pedidos-test.firebaseapp.com',
    storageBucket: 'restaurante-pedidos-test.appspot.com',
    iosBundleId: 'com.mobilepro.restau_pedidos',
  );
}

// 🧪 DATOS DE PRUEBA PARA LOGIN INMEDIATO:
// Email Admin: admin@test.com
// Password: Test123456
// 
// Email Empleado: empleado@test.com  
// Password: Test123456
//
// Código Empresa: TEST-2024-1234
